"""
Django settings for service project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-k+_)d+o5c$&do*u#xhg@!_8n(7p3k&0b=c%49_njat@mk-_gl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 
TEMPLATE_DEBUG = DEBUG

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'django_extensions',
  'chatbot',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_cas.middleware.CASMiddleware',
    'django.contrib.admindocs.middleware.XViewMiddleware',
]

ROOT_URLCONF = 'service.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
      os.path.join(BASE_DIR, 'templates'),
    ],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.core.context_processors.static',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#DATABASES = {
#  'default': {
#    'ENGINE': 'django.db.backends.mysql',
#    'NAME': 'cloud_manager',
#    'USER': 'cloud_manager_wr',
#    'PASSWORD':'JYKXgEn3PuWHH8ENRHKoOUmZZCyFEP4c',
#    'HOST':'10.118.9.148',
#    'PORT':'3306',
#  }
#}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

#AUTH_PASSWORD_VALIDATORS = [
#  {
#    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#  },
#  {
#    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#  },
#  {
#    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#  },
#  {
#    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#  },
#]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

import pytz
SHANGHAI_TZ = pytz.timezone("Asia/Shanghai")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/dist/'
STATICFILES_DIRS = (
  # Don't forget to use absolute paths, not relative paths.
  os.path.join(BASE_DIR, 'paas-ui/dist'),
)

import logging

LOGGING = {
  'version': 1,
  'disable_existing_loggers': False,
  'formatters': {
    'verbose': {
      'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
    }
  },
  'handlers': {
    'null': {
      'class': 'logging.NullHandler',
    },
    'rotating_file': {
      'level': 'INFO',
      'class': 'logging.handlers.RotatingFileHandler',
      'filename': 'log/debug.log',
      'maxBytes': 1024 * 1024 * 512,
      'backupCount': 14,
      'formatter': 'verbose'
    }
  },
  'loggers': {
    # Silence SuspiciousOperation.DisallowedHost exception ('Invalid
    # HTTP_HOST' header messages). Set the handler to 'null' so we don't
    # get those annoying emails
    'django.security.DisallowedHost': {
      'handlers': ['null'],
      'propagate': False,
    },
    'org': {
      'handlers': ['rotating_file'],
      'level': 'INFO',
      'propagate': True,
    },
    'iauth': {
      'handlers': ['rotating_file'],
      'level': 'INFO',
      'propagate': True,
    }
  }
}
